### ISSUE TITLE
Segmentation fault using lua_resolver

### ISSUE THREAD

**Issue by mrgonza78** [openresty/stream-lua-nginx-module#49]
ngninx.conf

```
worker_rlimit_core 500M;
working_directory /tmp/cores/;
error_log stderr debug;
daemon off;

events {
    use epoll;
    multi_accept on;
}

http {
}

stream {
    lua_resolver 8.8.8.8;

    server {
        listen 9999 reuseport backlog=1024 ;

        content_by_lua_block {
            local sock, err = ngx.socket.tcp()
            if sock then
                local res, err = sock:connect("google.com", 80)
                if res then
                    ngx.say("ok")
                end
            end
            if err then ngx.say(err) end
        }
    }
}
```

error.log

```
2016/11/14 23:45:25 [debug] 518#518: bind() 0.0.0.0:9999 #4
2016/11/14 23:45:25 [notice] 518#518: using the "epoll" event method
2016/11/14 23:45:25 [debug] 518#518: counter: 00007F1EB42A0080, 1
2016/11/14 23:45:25 [notice] 518#518: openresty/1.9.15.1
2016/11/14 23:45:25 [notice] 518#518: built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
2016/11/14 23:45:25 [notice] 518#518: OS: Linux 4.4.27-moby
2016/11/14 23:45:25 [notice] 518#518: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2016/11/14 23:45:25 [debug] 518#518: write: 7, 00007FFCC9903430, 4, 0
2016/11/14 23:45:25 [debug] 518#518: setproctitle: "nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /var/www/ring-socket-service/config/nginx.conf"
2016/11/14 23:45:25 [notice] 518#518: start worker processes
2016/11/14 23:45:25 [debug] 518#518: channel 3:7
2016/11/14 23:45:25 [notice] 518#518: start worker process 519
2016/11/14 23:45:25 [debug] 518#518: sigsuspend
2016/11/14 23:45:25 [debug] 519#519: notify eventfd: 9
2016/11/14 23:45:25 [debug] 519#519: eventfd: 10
2016/11/14 23:45:25 [debug] 519#519: malloc: 00007F1EB41C8DB0:6144
2016/11/14 23:45:25 [debug] 519#519: malloc: 00007F1EB41E0580:118784
2016/11/14 23:45:25 [debug] 519#519: malloc: 00007F1EB41FD590:49152
2016/11/14 23:45:25 [debug] 519#519: malloc: 00007F1EB42095A0:49152
2016/11/14 23:45:25 [debug] 519#519: epoll add event: fd:4 op:1 ev:00002001
2016/11/14 23:45:25 [debug] 519#519: REAPER: start reaper memstore message with tick time of 5 sec
2016/11/14 23:45:25 [debug] 519#519: REAPER: start reaper memstore nobuffer message with tick time of 2 sec
2016/11/14 23:45:25 [debug] 519#519: REAPER: start reaper chanhead with tick time of 4 sec
2016/11/14 23:45:25 [debug] 519#519: REAPER: start reaper chanhead churner with tick time of 10 sec
2016/11/14 23:45:25 [debug] 519#519: epoll add event: fd:5 op:1 ev:00002001
2016/11/14 23:45:25 [debug] 519#519: MEMSTORE:00: init memstore worker pid:519 slot:0 max workers :1 or 1
2016/11/14 23:45:25 [debug] 519#519: shmtx lock
2016/11/14 23:45:25 [debug] 519#519: MEMSTORE:00: found my procslot (ngx_process_slot 0, procslot 0)
2016/11/14 23:45:25 [debug] 519#519: MEMSTORE:00: shm: 00007F1EB41D4250, shdata: 00007F1EB0488000
2016/11/14 23:45:25 [debug] 519#519: shmtx unlock
2016/11/14 23:45:25 [debug] 519#519: WEBSOCKET_PUBLISHER:init WS publisher llist
2016/11/14 23:45:25 [debug] 519#519: malloc: 00007F1EB41BAB50:152
2016/11/14 23:45:25 [debug] 519#519: THINGCACHE: init fd_cache 00007F1EB41BAB50
2016/11/14 23:45:25 [debug] 519#519: epoll add event: fd:7 op:1 ev:00002001
2016/11/14 23:45:25 [debug] 519#519: setproctitle: "nginx: worker process"
2016/11/14 23:45:25 [debug] 519#519: worker cycle
2016/11/14 23:45:25 [debug] 519#519: epoll timer: -1
2016/11/14 23:45:27 [debug] 519#519: epoll: fd:4 ev:0001 d:00007F1EB41E0580
2016/11/14 23:45:27 [debug] 519#519: accept on 0.0.0.0:9999, ready: 1
2016/11/14 23:45:27 [debug] 519#519: posix_memalign: 00007F1EB41CA5C0:256 @16
2016/11/14 23:45:27 [debug] 519#519: *1 accept: 172.17.0.1:41198 fd:3
2016/11/14 23:45:27 [info] 519#519: *1 client 172.17.0.1:41198 connected to 0.0.0.0:9999
2016/11/14 23:45:27 [debug] 519#519: *1 tcp_nodelay
2016/11/14 23:45:27 [debug] 519#519: *1 posix_memalign: 00007F1EB41CA6D0:256 @16
2016/11/14 23:45:27 [debug] 519#519: *1 stream lua content handler fd:3
2016/11/14 23:45:27 [debug] 519#519: *1 malloc: 00007F1EB41CA7E0:368
2016/11/14 23:45:27 [debug] 519#519: *1 stream lua reset ctx
2016/11/14 23:45:27 [debug] 519#519: *1 stream lua creating new thread
2016/11/14 23:45:27 [debug] 519#519: *1 stream lua run thread, top:0
2016/11/14 23:45:27 [debug] 519#519: *1 stream lua tcp socket pool get keepalive peer
2016/11/14 23:45:27 [debug] 519#519: *1 stream lua tcp socket keepalive connection pool not found
2016/11/14 23:45:27 [debug] 519#519: *1 stream lua tcp socket connect timeout: 60000
2016/11/14 23:45:27 [debug] 519#519: malloc: 00007F1EB41CA960:224
2016/11/14 23:45:27 [debug] 519#519: resolve: "google.com"
2016/11/14 23:45:27 [debug] 519#519: malloc: 00007F1EB41CAA50:184
2016/11/14 23:45:27 [debug] 519#519: malloc: 00007F1EB41CAB10:10
2016/11/14 23:45:27 [debug] 519#519: malloc: 00007F1EB41CAB30:56
2016/11/14 23:45:27 [debug] 519#519: resolve: "google.com" A 15358
2016/11/14 23:45:27 [debug] 519#519: resolve: "google.com" AAAA 51876
2016/11/14 23:45:27 [debug] 519#519: UDP socket 11
2016/11/14 23:45:27 [debug] 519#519: connect to 8.8.8.8:53, fd:11 #2
2016/11/14 23:45:27 [debug] 519#519: epoll add event: fd:11 op:1 ev:80002001
2016/11/14 23:45:27 [debug] 519#519: send: fd:11 28 of 28
2016/11/14 23:45:27 [debug] 519#519: send: fd:11 28 of 28
2016/11/14 23:45:27 [debug] 519#519: malloc: 00007F1EB41BABF0:96
2016/11/14 23:45:27 [debug] 519#519: event timer add: -1: 30000:1479167157512
2016/11/14 23:45:27 [debug] 519#519: event timer add: -1: 5000:1479167132512
2016/11/14 23:45:27 [debug] 519#519: *1 stream lua resume returned 1
2016/11/14 23:45:27 [debug] 519#519: *1 stream lua thread yielded
2016/11/14 23:45:27 [debug] 519#519: *1 stream lua finalize: rc=-4
2016/11/14 23:45:27 [debug] 519#519: accept() not ready (11: Resource temporarily unavailable)
2016/11/14 23:45:27 [debug] 519#519: timer delta: 2215
2016/11/14 23:45:27 [debug] 519#519: worker cycle
2016/11/14 23:45:27 [debug] 519#519: epoll timer: 5000
2016/11/14 23:45:27 [debug] 519#519: epoll: fd:11 ev:0001 d:00007F1EB41E0920
2016/11/14 23:45:27 [debug] 519#519: recv: fd:11 56 of 4096
2016/11/14 23:45:27 [debug] 519#519: resolver DNS response 51876 fl:8180 1/1/0/0
2016/11/14 23:45:27 [debug] 519#519: resolver DNS response qt:28 cl:1
2016/11/14 23:45:27 [debug] 519#519: malloc: 00007F1EB41CAB70:10
2016/11/14 23:45:27 [debug] 519#519: resolver qs:google.com
2016/11/14 23:45:27 [debug] 519#519: resolver naddrs:1 cname:0000000000000000 ttl:175
2016/11/14 23:45:27 [debug] 519#519: recv: fd:11 124 of 4096
2016/11/14 23:45:27 [debug] 519#519: resolver DNS response 15358 fl:8180 1/6/0/0
2016/11/14 23:45:27 [debug] 519#519: resolver DNS response qt:1 cl:1
2016/11/14 23:45:27 [debug] 519#519: malloc: 00007F1EB41CAB70:10
2016/11/14 23:45:27 [debug] 519#519: resolver qs:google.com
2016/11/14 23:45:27 [debug] 519#519: resolver naddrs:6 cname:0000000000000000 ttl:175
2016/11/14 23:45:27 [debug] 519#519: malloc: 00007F1EB41CAB70:24
2016/11/14 23:45:27 [debug] 519#519: malloc: 00007F1EB41CAB90:280
2016/11/14 23:45:27 [debug] 519#519: malloc: 00007F1EB41CACB0:770
2016/11/14 23:45:27 [debug] 519#519: *1 stream lua tcp socket resolve handler
2016/11/14 23:45:27 [debug] 519#519: *1 name was resolved to 64.233.186.139
2016/11/14 23:45:27 [notice] 518#518: signal 17 (SIGCHLD) received
2016/11/14 23:45:27 [alert] 518#518: worker process 519 exited on signal 11 (core dumped)
2016/11/14 23:45:27 [debug] 518#518: shmtx forced unlock
2016/11/14 23:45:27 [debug] 518#518: shmtx forced unlock
2016/11/14 23:45:27 [debug] 518#518: wake up, sigio 0
2016/11/14 23:45:27 [debug] 518#518: reap children
2016/11/14 23:45:27 [debug] 518#518: child: 0 519 e:0 t:1 d:0 r:1 j:0
2016/11/14 23:45:27 [debug] 518#518: channel 3:7
2016/11/14 23:45:27 [notice] 518#518: start worker process 520
2016/11/14 23:45:27 [debug] 518#518: sigsuspend
2016/11/14 23:45:27 [debug] 520#520: notify eventfd: 9
2016/11/14 23:45:27 [debug] 520#520: eventfd: 10
2016/11/14 23:45:27 [debug] 520#520: malloc: 00007F1EB41C8DB0:6144
2016/11/14 23:45:27 [debug] 520#520: malloc: 00007F1EB41E0580:118784
2016/11/14 23:45:27 [debug] 520#520: malloc: 00007F1EB41FD590:49152
2016/11/14 23:45:27 [debug] 520#520: malloc: 00007F1EB42095A0:49152
2016/11/14 23:45:27 [debug] 520#520: epoll add event: fd:4 op:1 ev:00002001
2016/11/14 23:45:27 [debug] 520#520: REAPER: start reaper memstore message with tick time of 5 sec
2016/11/14 23:45:27 [debug] 520#520: REAPER: start reaper memstore nobuffer message with tick time of 2 sec
2016/11/14 23:45:27 [debug] 520#520: REAPER: start reaper chanhead with tick time of 4 sec
2016/11/14 23:45:27 [debug] 520#520: REAPER: start reaper chanhead churner with tick time of 10 sec
2016/11/14 23:45:27 [debug] 520#520: epoll add event: fd:5 op:1 ev:00002001
2016/11/14 23:45:27 [debug] 520#520: MEMSTORE:00: init memstore worker pid:520 slot:0 max workers :1 or 1
2016/11/14 23:45:27 [debug] 520#520: shmtx lock
2016/11/14 23:45:27 [debug] 520#520: MEMSTORE:00: found my procslot (ngx_process_slot 0, procslot 0)
2016/11/14 23:45:27 [debug] 520#520: MEMSTORE:00: shm: 00007F1EB41D4250, shdata: 00007F1EB0488000
2016/11/14 23:45:27 [debug] 520#520: shmtx unlock
2016/11/14 23:45:27 [debug] 520#520: WEBSOCKET_PUBLISHER:init WS publisher llist
2016/11/14 23:45:27 [debug] 520#520: malloc: 00007F1EB41BAB50:152
2016/11/14 23:45:27 [debug] 520#520: THINGCACHE: init fd_cache 00007F1EB41BAB50
2016/11/14 23:45:27 [debug] 520#520: epoll add event: fd:7 op:1 ev:00002001
2016/11/14 23:45:27 [debug] 520#520: setproctitle: "nginx: worker process"
2016/11/14 23:45:27 [debug] 520#520: worker cycle
2016/11/14 23:45:27 [debug] 520#520: epoll timer: -1
```

Core dump
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ngx_sock_ntop (sa=0x0, socklen=3021778206, text=text@entry=0x7ffcc9901ff0 "64.233.186.139", len=len@entry=113, port=port@entry=0) at src/core/ngx_inet.c:194
194 src/core/ngx_inet.c: No such file or directory.
(gdb) backtrace
#0  ngx_sock_ntop (sa=0x0, socklen=3021778206, text=text@entry=0x7ffcc9901ff0 "64.233.186.139", len=len@entry=113, port=port@entry=0) at src/core/ngx_inet.c:194
#1  0x00000000005aa706 in ngx_stream_lua_socket_resolve_handler (ctx=0x7f1eb41ca960) at /tmp/stream-lua-nginx-module-0.0.1/src/ngx_stream_lua_socket_tcp.c:835
#2  0x000000000047321b in ngx_resolver_process_a (ans=<optimized out>, trunc=<optimized out>, nan=<optimized out>, qtype=<optimized out>, code=<optimized out>,
    ident=<optimized out>, n=<optimized out>, buf=0x7ffcc99020b0 "\257", r=<optimized out>) at src/core/ngx_resolver.c:2431
#3  ngx_resolver_process_response (r=<optimized out>, buf=buf@entry=0x7ffcc9902190 ";\376\201\200", n=<optimized out>, tcp=tcp@entry=0) at src/core/ngx_resolver.c:1835
#4  0x00000000004745b5 in ngx_resolver_udp_read (rev=0x7f1eb41fd710) at src/core/ngx_resolver.c:1576
#5  0x0000000000482699 in ngx_epoll_process_events (cycle=0x7f1eb41bbdc0, timer=<optimized out>, flags=<optimized out>) at src/event/modules/ngx_epoll_module.c:822
#6  0x00000000004786d7 in ngx_process_events_and_timers (cycle=cycle@entry=0x7f1eb41bbdc0) at src/event/ngx_event.c:242
#7  0x0000000000480035 in ngx_worker_process_cycle (cycle=cycle@entry=0x7f1eb41bbdc0, data=data@entry=0x0) at src/os/unix/ngx_process_cycle.c:753
#8  0x000000000047eb00 in ngx_spawn_process (cycle=cycle@entry=0x7f1eb41bbdc0, proc=proc@entry=0x47fff0 <ngx_worker_process_cycle>, data=data@entry=0x0,
    name=name@entry=0x786660 "worker process", respawn=respawn@entry=-3) at src/os/unix/ngx_process.c:198
#9  0x00000000004802a4 in ngx_start_worker_processes (cycle=cycle@entry=0x7f1eb41bbdc0, n=1, type=type@entry=-3) at src/os/unix/ngx_process_cycle.c:358
#10 0x0000000000480fdf in ngx_master_process_cycle (cycle=cycle@entry=0x7f1eb41bbdc0) at src/os/unix/ngx_process_cycle.c:130
#11 0x0000000000459d39 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:367
```

nginx -V
```
nginx version: openresty/1.9.15.1
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
built with OpenSSL 1.0.2j  26 Sep 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-debug --with-cc-opt='-DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC -O2' --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.59 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.30 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.05 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.5 --add-module=../ngx_lua_upstream-0.05 --add-module=../headers-more-nginx-module-0.30 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.17 --add-module=../redis2-nginx-module-0.13 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.07 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-openssl=/tmp/openssl-1.0.2j --with-pcre=/tmp/pcre-8.39 --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-ipv6 --with-mail --with-mail_ssl_module --with-md5-asm --with-pcre-jit --with-sha1-asm --with-stream --with-stream_ssl_module --with-threads --add-module=/tmp/nchan-0.99.16 --add-module=/tmp/stream-lua-nginx-module-0.0.1
```

**Comment by mrgonza78** [comment]
Closing ticket as this is fixed in master (Fixed here: https://github.com/openresty/stream-lua-nginx-module/commit/9f0cc4d)
