### ISSUE TITLE
Nginx crash because of call ngx_stream_lua_finalize_session more than once

### ISSUE THREAD

**Issue by qlee001** [openresty/stream-lua-nginx-module#63]
Nginx config file like bellow. It's the same as TSET12 in t/106-timer.t

```
worker_processes  1;
daemon off;
master_process off;
events {
    use epoll;
}
stream {
    server {
        listen 1988;
        content_by_lua_block {
            local function fail (...)
                ngx.log(ngx.ERR, ...)
            end
            local function handle()
                function f()
                    print("hello in thread")
                    return "done"
                end

                local t, err = ngx.thread.spawn(f)
                if not t then
                    fail("failed to spawn thread: ", err)
                    return
                end

                print("thread created: ", coroutine.status(t))

   
                collectgarbage()

                local ok, res = ngx.thread.wait(t)
                if not ok then
                    fail("failed to run thread: ", res)
                    return
                end

                print("wait result: ", res)
            end
            
            local ok, err = ngx.timer.at(0.01, handle)
            if not ok then
                ngx.say("failed to set timer: ", err)
                return
            end
            ngx.say("registered timer")
        }
    }
}
```

Nginx receive segment fault when process request.

gdb debuginfo like this 

```

Breakpoint 1, ngx_stream_lua_finalize_session (s=0x7ffff7efb1f0, rc=0) at /home/kenan/Git/stream-lua-nginx-module/src/ngx_stream_lua_util.c:596
596	    ctx = ngx_stream_get_module_ctx(s, ngx_stream_lua_module);
(gdb) bt
#0  ngx_stream_lua_finalize_session (s=0x7ffff7efb1f0, rc=0) at /home/kenan/Git/stream-lua-nginx-module/src/ngx_stream_lua_util.c:596
#1  0x00000000005a70a7 in ngx_stream_lua_run_posted_threads (c=0x7ffff7f09278, L=0x40000378, s=0x7ffff7efb1f0, ctx=0x7ffff7ef4d30) at /home/kenan/Git/stream-lua-nginx-module/src/ngx_stream_lua_util.c:1732
#2  0x00000000005ceb6a in ngx_stream_lua_timer_handler (ev=0x0) at /home/kenan/Git/stream-lua-nginx-module/src/ngx_stream_lua_timer.c:490
#3  0x0000000000455fa0 in ngx_event_expire_timers () at src/event/ngx_event_timer.c:94
#4  0x000000000045393b in ngx_process_events_and_timers (cycle=0x7ffff7ef59c0) at src/event/ngx_event.c:256
#5  0x00000000004618a8 in ngx_single_process_cycle (cycle=0x7ffff7ef59c0) at src/os/unix/ngx_process_cycle.c:309
#6  0x000000000041cfa0 in main (argc=3, argv=0x7fffffffe4f8) at src/core/nginx.c:364
(gdb) c
Continuing.

Breakpoint 1, ngx_stream_lua_finalize_session (s=0x7ffff7efb1f0, rc=-4) at /home/kenan/Git/stream-lua-nginx-module/src/ngx_stream_lua_util.c:596
596	    ctx = ngx_stream_get_module_ctx(s, ngx_stream_lua_module);
(gdb) bt
#0  ngx_stream_lua_finalize_session (s=0x7ffff7efb1f0, rc=-4) at /home/kenan/Git/stream-lua-nginx-module/src/ngx_stream_lua_util.c:596
#1  0x00000000005ceb97 in ngx_stream_lua_timer_handler (ev=0x0) at /home/kenan/Git/stream-lua-nginx-module/src/ngx_stream_lua_timer.c:496
#2  0x0000000000455fa0 in ngx_event_expire_timers () at src/event/ngx_event_timer.c:94
#3  0x000000000045393b in ngx_process_events_and_timers (cycle=0x7ffff7ef59c0) at src/event/ngx_event.c:256
#4  0x00000000004618a8 in ngx_single_process_cycle (cycle=0x7ffff7ef59c0) at src/os/unix/ngx_process_cycle.c:309
#5  0x000000000041cfa0 in main (argc=3, argv=0x7fffffffe4f8) at src/core/nginx.c:364
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00000000005a5084 in ngx_stream_lua_finalize_session (s=0x7ffff7efb1f0, rc=-4) at /home/kenan/Git/stream-lua-nginx-module/src/ngx_stream_lua_util.c:597
597	    if (ctx && ctx->cur_co_ctx) {
(gdb) 

```

The function ngx_stream_finalize_session was called twice. Unlike the HTTP module, ngx_stream_session_t has not member as a reference count(like r->count), so ngx_stream_lua_finalize_session must be called only once.

**Comment by doujiang24** [comment]
@qlee001 Which version of nginx are you using?
I suggestion you are using 1.11.7 or higher?
The current official branch is based on nginx 1.9.7 / 1.11.2, so you'd better to use it with nginx-1.9.7/1.11.2.
Here is my personal branch work on nginx 1.11.7, yeah, not finished, still have some work to do to create a PR, feel free to try:
https://github.com/doujiang24/stream-lua-nginx-module/commits/nginx-1.11.7

**Comment by qlee001** [comment]
@doujiang24 
When use nginx-1.9.7, no segment fault accurred, but I think it's not ok here.The function was called twice, and the ngx_stream_session_t struct was used after freed.

Use cgdb here.You can see the ngx_stream_sessison_t struct(pointer 0x7ffff7ef4d90) was freed by ngx_free，then use again. 
I also confused why use a freed memory here.

```
586│
 587│     ngx_stream_lua_finalize_threads(s, ctx, L);
 588│ }
 589│
 590│
 591│ void
 592│ ngx_stream_lua_finalize_session(ngx_stream_session_t *s, ngx_int_t rc)
 593│ {
 594│     ngx_stream_lua_ctx_t              *ctx;
 595│
 596├>    ctx = ngx_stream_get_module_ctx(s, ngx_stream_lua_module);
 597│     if (ctx && ctx->cur_co_ctx) {
 598│         ngx_stream_lua_cleanup_pending_operation(ctx->cur_co_ctx);
 599│     }
 600│
 601│     if (s->connection->fd != (ngx_socket_t) -1) {
 602│         ngx_stream_lua_finalize_real_session(s, rc);
 603│         return;
 604│     }
 605│
 606│     ngx_stream_lua_finalize_fake_session(s, rc);
/home/kenan/Git/stream-lua-nginx-module/src/ngx_stream_lua_util.c                                                                                                                                                   
$7 = {next = 0x7ffff7efb350, alloc = 0x7ffff7ef4d90}
(gdb) n
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) p l->alloc
$8 = (void *) 0x7ffff7efb060
(gdb) n          
(gdb) 
(gdb) 
(gdb) p l->alloc
$9 = (void *) 0x7ffff7ef4d90
(gdb) c
Continuing.

Breakpoint 1, ngx_stream_lua_finalize_session (s=0x7ffff7ef4d90, rc=-4) at /home/kenan/Git/stream-lua-nginx-module/src/ngx_stream_lua_util.c:596
(gdb) p s[0]
$10 = {signature = 0, connection = 0x7ffff7f01b68, received = 0, log_handler = 0x0, ctx = 0x7ffff7efb060, main_conf = 0x7ffff7ef7310, srv_conf = 0x7ffff7ef7b98, upstream = 0x0}
(gdb) 
```

**Comment by agentzh** [comment]
@qlee001 Will you use valgrind memcheck to confirm this? Also remember to apply the no-pool patch for the nginx core. Your cgdb session output is not very readable for me.

**Comment by qlee001** [comment]
valgrind results

```
root@PC:/usr/local/nginx# valgrind ./sbin/nginx -c ./conf/nginx2.conf 
==3701== Memcheck, a memory error detector
==3701== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==3701== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==3701== Command: ./sbin/nginx -c ./conf/nginx2.conf
==3701== 
==3701== Conditional jump or move depends on uninitialised value(s)
==3701==    at 0x529D8C3: ??? (in /usr/local/lib/libluajit-5.1.so.2.1.0)
==3701==    by 0x52A8ABB: lua_setfield (in /usr/local/lib/libluajit-5.1.so.2.1.0)
==3701==    by 0x583C9A: ngx_stream_lua_cache_store_code (ngx_stream_lua_cache.c:116)
==3701==    by 0x583DD7: ngx_stream_lua_cache_loadbuffer (ngx_stream_lua_cache.c:184)
==3701==    by 0x57D1E5: ngx_stream_lua_content_handler_inline (ngx_stream_lua_contentby.c:64)
==3701==    by 0x57D695: ngx_stream_lua_content_handler (ngx_stream_lua_contentby.c:236)
==3701==    by 0x4FD3C4: ngx_stream_init_session (ngx_stream_handler.c:231)
==3701==    by 0x4FD312: ngx_stream_init_connection (ngx_stream_handler.c:210)
==3701==    by 0x44A89D: ngx_event_accept (ngx_event_accept.c:356)
==3701==    by 0x4571E3: ngx_epoll_process_events (ngx_epoll_module.c:822)
==3701==    by 0x447189: ngx_process_events_and_timers (ngx_event.c:242)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701== 
==3701== Invalid read of size 8
==3701==    at 0x57E8BC: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:596)
==3701==    by 0x5A8367: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:496)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Address 0x69ad170 is 32 bytes inside a block of size 64 free'd
==3701==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x41E461: ngx_destroy_pool (ngx_palloc.c:76)
==3701==    by 0x581026: ngx_stream_lua_close_fake_connection (ngx_stream_lua_util.c:2029)
==3701==    by 0x580D77: ngx_stream_lua_close_fake_session (ngx_stream_lua_util.c:1941)
==3701==    by 0x580D42: ngx_stream_lua_finalize_fake_session (ngx_stream_lua_util.c:1929)
==3701==    by 0x57E930: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:606)
==3701==    by 0x580902: ngx_stream_lua_run_posted_threads (ngx_stream_lua_util.c:1732)
==3701==    by 0x5A833A: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:490)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Block was alloc'd at
==3701==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x44E076: ngx_alloc (ngx_alloc.c:22)
==3701==    by 0x41E5CC: ngx_malloc (ngx_palloc.c:137)
==3701==    by 0x41E57E: ngx_palloc (ngx_palloc.c:120)
==3701==    by 0x41E7F5: ngx_pcalloc (ngx_palloc.c:215)
==3701==    by 0x582CFF: ngx_stream_lua_create_fake_session (ngx_stream_lua_util.c:3080)
==3701==    by 0x5A8002: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:391)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701== 
==3701== Invalid read of size 8
==3701==    at 0x57E8CE: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:596)
==3701==    by 0x5A8367: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:496)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Address 0x69ad240 is 32 bytes inside a block of size 88 free'd
==3701==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x41E461: ngx_destroy_pool (ngx_palloc.c:76)
==3701==    by 0x581026: ngx_stream_lua_close_fake_connection (ngx_stream_lua_util.c:2029)
==3701==    by 0x580D77: ngx_stream_lua_close_fake_session (ngx_stream_lua_util.c:1941)
==3701==    by 0x580D42: ngx_stream_lua_finalize_fake_session (ngx_stream_lua_util.c:1929)
==3701==    by 0x57E930: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:606)
==3701==    by 0x580902: ngx_stream_lua_run_posted_threads (ngx_stream_lua_util.c:1732)
==3701==    by 0x5A833A: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:490)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Block was alloc'd at
==3701==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x44E076: ngx_alloc (ngx_alloc.c:22)
==3701==    by 0x41E5CC: ngx_malloc (ngx_palloc.c:137)
==3701==    by 0x41E57E: ngx_palloc (ngx_palloc.c:120)
==3701==    by 0x41E7F5: ngx_pcalloc (ngx_palloc.c:215)
==3701==    by 0x582D33: ngx_stream_lua_create_fake_session (ngx_stream_lua_util.c:3085)
==3701==    by 0x5A8002: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:391)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701== 
==3701== Invalid read of size 8
==3701==    at 0x57E8E0: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:597)
==3701==    by 0x5A8367: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:496)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Address 0x69ad360 is 80 bytes inside a block of size 360 free'd
==3701==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x41E461: ngx_destroy_pool (ngx_palloc.c:76)
==3701==    by 0x581026: ngx_stream_lua_close_fake_connection (ngx_stream_lua_util.c:2029)
==3701==    by 0x580D77: ngx_stream_lua_close_fake_session (ngx_stream_lua_util.c:1941)
==3701==    by 0x580D42: ngx_stream_lua_finalize_fake_session (ngx_stream_lua_util.c:1929)
==3701==    by 0x57E930: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:606)
==3701==    by 0x580902: ngx_stream_lua_run_posted_threads (ngx_stream_lua_util.c:1732)
==3701==    by 0x5A833A: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:490)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Block was alloc'd at
==3701==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x44E076: ngx_alloc (ngx_alloc.c:22)
==3701==    by 0x41E5CC: ngx_malloc (ngx_palloc.c:137)
==3701==    by 0x41E57E: ngx_palloc (ngx_palloc.c:120)
==3701==    by 0x5A71E4: ngx_stream_lua_create_ctx (ngx_stream_lua_util.h:174)
==3701==    by 0x5A812B: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:425)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701== 
==3701== Invalid read of size 8
==3701==    at 0x57E8ED: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:598)
==3701==    by 0x5A8367: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:496)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Address 0x69ad360 is 80 bytes inside a block of size 360 free'd
==3701==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x41E461: ngx_destroy_pool (ngx_palloc.c:76)
==3701==    by 0x581026: ngx_stream_lua_close_fake_connection (ngx_stream_lua_util.c:2029)
==3701==    by 0x580D77: ngx_stream_lua_close_fake_session (ngx_stream_lua_util.c:1941)
==3701==    by 0x580D42: ngx_stream_lua_finalize_fake_session (ngx_stream_lua_util.c:1929)
==3701==    by 0x57E930: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:606)
==3701==    by 0x580902: ngx_stream_lua_run_posted_threads (ngx_stream_lua_util.c:1732)
==3701==    by 0x5A833A: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:490)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Block was alloc'd at
==3701==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x44E076: ngx_alloc (ngx_alloc.c:22)
==3701==    by 0x41E5CC: ngx_malloc (ngx_palloc.c:137)
==3701==    by 0x41E57E: ngx_palloc (ngx_palloc.c:120)
==3701==    by 0x5A71E4: ngx_stream_lua_create_ctx (ngx_stream_lua_util.h:174)
==3701==    by 0x5A812B: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:425)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701== 
==3701== Invalid read of size 8
==3701==    at 0x57D97A: ngx_stream_lua_cleanup_pending_operation (ngx_stream_lua_util.h:257)
==3701==    by 0x57E8F8: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:598)
==3701==    by 0x5A8367: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:496)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Address 0x69ad390 is 128 bytes inside a block of size 360 free'd
==3701==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x41E461: ngx_destroy_pool (ngx_palloc.c:76)
==3701==    by 0x581026: ngx_stream_lua_close_fake_connection (ngx_stream_lua_util.c:2029)
==3701==    by 0x580D77: ngx_stream_lua_close_fake_session (ngx_stream_lua_util.c:1941)
==3701==    by 0x580D42: ngx_stream_lua_finalize_fake_session (ngx_stream_lua_util.c:1929)
==3701==    by 0x57E930: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:606)
==3701==    by 0x580902: ngx_stream_lua_run_posted_threads (ngx_stream_lua_util.c:1732)
==3701==    by 0x5A833A: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:490)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Block was alloc'd at
==3701==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x44E076: ngx_alloc (ngx_alloc.c:22)
==3701==    by 0x41E5CC: ngx_malloc (ngx_palloc.c:137)
==3701==    by 0x41E57E: ngx_palloc (ngx_palloc.c:120)
==3701==    by 0x5A71E4: ngx_stream_lua_create_ctx (ngx_stream_lua_util.h:174)
==3701==    by 0x5A812B: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:425)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701== 
==3701== Invalid read of size 8
==3701==    at 0x57E8FD: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:601)
==3701==    by 0x5A8367: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:496)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Address 0x69ad158 is 8 bytes inside a block of size 64 free'd
==3701==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x41E461: ngx_destroy_pool (ngx_palloc.c:76)
==3701==    by 0x581026: ngx_stream_lua_close_fake_connection (ngx_stream_lua_util.c:2029)
==3701==    by 0x580D77: ngx_stream_lua_close_fake_session (ngx_stream_lua_util.c:1941)
==3701==    by 0x580D42: ngx_stream_lua_finalize_fake_session (ngx_stream_lua_util.c:1929)
==3701==    by 0x57E930: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:606)
==3701==    by 0x580902: ngx_stream_lua_run_posted_threads (ngx_stream_lua_util.c:1732)
==3701==    by 0x5A833A: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:490)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Block was alloc'd at
==3701==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x44E076: ngx_alloc (ngx_alloc.c:22)
==3701==    by 0x41E5CC: ngx_malloc (ngx_palloc.c:137)
==3701==    by 0x41E57E: ngx_palloc (ngx_palloc.c:120)
==3701==    by 0x41E7F5: ngx_pcalloc (ngx_palloc.c:215)
==3701==    by 0x582CFF: ngx_stream_lua_create_fake_session (ngx_stream_lua_util.c:3080)
==3701==    by 0x5A8002: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:391)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701== 
==3701== Invalid read of size 8
==3701==    at 0x580C7B: ngx_stream_lua_finalize_fake_session (ngx_stream_lua_util.c:1886)
==3701==    by 0x57E930: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:606)
==3701==    by 0x5A8367: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:496)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Address 0x69ad158 is 8 bytes inside a block of size 64 free'd
==3701==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x41E461: ngx_destroy_pool (ngx_palloc.c:76)
==3701==    by 0x581026: ngx_stream_lua_close_fake_connection (ngx_stream_lua_util.c:2029)
==3701==    by 0x580D77: ngx_stream_lua_close_fake_session (ngx_stream_lua_util.c:1941)
==3701==    by 0x580D42: ngx_stream_lua_finalize_fake_session (ngx_stream_lua_util.c:1929)
==3701==    by 0x57E930: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:606)
==3701==    by 0x580902: ngx_stream_lua_run_posted_threads (ngx_stream_lua_util.c:1732)
==3701==    by 0x5A833A: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:490)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Block was alloc'd at
==3701==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x44E076: ngx_alloc (ngx_alloc.c:22)
==3701==    by 0x41E5CC: ngx_malloc (ngx_palloc.c:137)
==3701==    by 0x41E57E: ngx_palloc (ngx_palloc.c:120)
==3701==    by 0x41E7F5: ngx_pcalloc (ngx_palloc.c:215)
==3701==    by 0x582CFF: ngx_stream_lua_create_fake_session (ngx_stream_lua_util.c:3080)
==3701==    by 0x5A8002: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:391)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701== 
==3701== Invalid read of size 8
==3701==    at 0x580C8B: ngx_stream_lua_finalize_fake_session (ngx_stream_lua_util.c:1888)
==3701==    by 0x57E930: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:606)
==3701==    by 0x5A8367: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:496)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Address 0x69ad070 is 0 bytes inside a block of size 80 free'd
==3701==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x41E461: ngx_destroy_pool (ngx_palloc.c:76)
==3701==    by 0x581026: ngx_stream_lua_close_fake_connection (ngx_stream_lua_util.c:2029)
==3701==    by 0x580D77: ngx_stream_lua_close_fake_session (ngx_stream_lua_util.c:1941)
==3701==    by 0x580D42: ngx_stream_lua_finalize_fake_session (ngx_stream_lua_util.c:1929)
==3701==    by 0x57E930: ngx_stream_lua_finalize_session (ngx_stream_lua_util.c:606)
==3701==    by 0x580902: ngx_stream_lua_run_posted_threads (ngx_stream_lua_util.c:1732)
==3701==    by 0x5A833A: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:490)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701==  Block was alloc'd at
==3701==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3701==    by 0x44E076: ngx_alloc (ngx_alloc.c:22)
==3701==    by 0x41E5CC: ngx_malloc (ngx_palloc.c:137)
==3701==    by 0x41E57E: ngx_palloc (ngx_palloc.c:120)
==3701==    by 0x41E7F5: ngx_pcalloc (ngx_palloc.c:215)
==3701==    by 0x582C48: ngx_stream_lua_create_fake_connection (ngx_stream_lua_util.c:3040)
==3701==    by 0x5A7F8F: ngx_stream_lua_timer_handler (ngx_stream_lua_timer.c:380)
==3701==    by 0x44974B: ngx_event_expire_timers (ngx_event_timer.c:94)
==3701==    by 0x44720B: ngx_process_events_and_timers (ngx_event.c:256)
==3701==    by 0x45372F: ngx_single_process_cycle (ngx_process_cycle.c:309)
==3701==    by 0x41ACE2: main (nginx.c:356)
==3701== 
```

**Comment by dndx** [comment]
Related to the old stream_lua. Please use the newly rewritten stream_lua that works with NGINX core 1.13.x.
